import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/components/provider";


const JetBrainMono = JetBrains_Mono({
  variable: "--jetBrainsMono",
  subsets: ["latin"]
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${JetBrainMono.variable} antialiased`}
      >
        <Provider>

          {children}
        </Provider>
      </body>
    </html>
  );
}
